name = "1_data_prep"
description = "Ingest raw SMILES data and compute descriptors"
outputs = ["outputs/processed_data.pkl", "outputs/data.json", "outputs/report.html"]

[container]
image = "chiral.sakuracr.jp/qsar-hybrid-model:v3"
use_gpu = true

[scripts]
run = "run.sh"

[params.input_csv]
type = "string"
default = " "
hint = "Name of the input CSV file in input_files directory"
