name = "2 Protein Preparation"
description = "Extracts Chain A and the NAD cofactor from a PDB file."
inputs = ["*.pdb"]
outputs = ["*.pdb"]

[container]
image = "ghcr.io/chiral-data/smina:2025_11_06"

[scripts]
run = "run.sh"
