# Node 5: Predict binding pockets using P2Rank
depends_on = ["01_ProteinInput"]
inputs = ["*.pdb"]
outputs = ["*.csv", "*.log", "*.txt"]

[container]
docker_image = "esraasuliman/workflow-esraa-node5:1.0"

[scripts]
