name = "Model Training"
description = "Train a Deep Neural Network (DNN) to predict binding affinity (pIC50)."
outputs = ["outputs/model.h5", "outputs/data.json", "outputs/report.html"]

[container]
image = "chiral.sakuracr.jp/qsar:20260107_v1"

[scripts]
run = "run.sh"