name = "6 Docking Report"
description = "Generates a report from the docking results"
inputs = ["docking_results", "results"]
outputs = ["results"]

[container]
image = "chiral.sakuracr.jp/smina:2025_11_06"

[scripts]
run = "run.sh"
