#!/usr/bin/env python3
"""
Visualize chemical space summary - Node 5

Usage:
    python visualize.py [chemspace.pkl] [output.html]

Default:
    python visualize.py chemspace.pkl chemspace_viz.html
"""

import sys
import pickle
from pathlib import Path

try:
    import cloudpickle
except ImportError:
    cloudpickle = None


def load_chemspace(pkl_path):
    """Load chemical space from pickle file."""
    try:
        if cloudpickle:
            with open(pkl_path, 'rb') as f:
                return cloudpickle.load(f)
        else:
            with open(pkl_path, 'rb') as f:
                return pickle.load(f)
    except:
        with open(pkl_path, 'rb') as f:
            return pickle.load(f)


HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Chemical Space Summary</title>
    <style>
        body {{
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            background: #1a1a2e; color: #eee; padding: 20px;
        }}
        .header {{ text-align: center; padding: 20px; background: #16213e; border-radius: 12px; margin-bottom: 20px; }}
        .header h1 {{ color: #ea7d3d; }}
        .container {{ max-width: 900px; margin: 0 auto; }}
        .stats {{ display: grid; grid-template-columns: repeat(3, 1fr); gap: 20px; margin-bottom: 20px; }}
        .stat {{ background: #16213e; padding: 30px; border-radius: 12px; text-align: center; border: 1px solid #2a2a4a; }}
        .stat .value {{ font-size: 48px; color: #ea7d3d; font-weight: bold; }}
        .stat .label {{ color: #888; font-size: 16px; margin-top: 8px; }}
        .info {{ background: #16213e; padding: 24px; border-radius: 12px; border: 1px solid #2a2a4a; }}
        .info h3 {{ color: #ea7d3d; margin-bottom: 16px; }}
        .info p {{ line-height: 1.8; color: #ccc; }}
        .next-step {{ background: #16213e; padding: 24px; border-radius: 12px; margin-top: 20px; border-left: 4px solid #ea7d3d; }}
        .next-step h4 {{ color: #ea7d3d; margin-bottom: 12px; }}
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>Chemical Space Summary</h1>
            <p>Node 5: Chemical Space Creation</p>
        </div>
        <div class="stats">
            <div class="stat">
                <div class="value">{num_molecules}</div>
                <div class="label">Generated Molecules</div>
            </div>
            <div class="stat">
                <div class="value">{has_scaffold}</div>
                <div class="label">Scaffold Loaded</div>
            </div>
            <div class="stat">
                <div class="value">{has_protein}</div>
                <div class="label">Protein Loaded</div>
            </div>
        </div>
        <div class="info">
            <h3>Chemical Space Information</h3>
            <p>The chemical space has been generated by combining the scaffold with various linkers and R-groups.</p>
            <p>Total of <strong>{num_molecules}</strong> unique molecules have been created in this combinatorial library.</p>
            <p>These molecules are ready for active learning docking evaluation in the next node.</p>
        </div>
        <div class="next-step">
            <h4>Next Step</h4>
            <p>Run Node 6 (Active Learning Docking) to evaluate these molecules and generate binding affinity predictions.</p>
            <p>After evaluation, visualize the results with: <code>python visualize.py chemspace_evaluated.sdf</code></p>
        </div>
    </div>
</body>
</html>
"""


def main():
    input_file = sys.argv[1] if len(sys.argv) > 1 else "chemspace.pkl"
    output_file = sys.argv[2] if len(sys.argv) > 2 else "chemspace_viz.html"

    if not Path(input_file).exists():
        print(f"Error: {input_file} not found")
        sys.exit(1)

    chemspace = load_chemspace(input_file)

    # Extract information
    num_molecules = 0
    has_scaffold = "No"
    has_protein = "No"

    if hasattr(chemspace, 'df') and chemspace.df is not None:
        num_molecules = len(chemspace.df)

    if hasattr(chemspace, 'scaffold') and chemspace.scaffold is not None:
        has_scaffold = "Yes"

    if hasattr(chemspace, 'protein') or hasattr(chemspace, 'receptor'):
        has_protein = "Yes"

    html = HTML_TEMPLATE.format(
        num_molecules=num_molecules,
        has_scaffold=has_scaffold,
        has_protein=has_protein
    )

    with open(output_file, 'w') as f:
        f.write(html)

    print(f"Generated: {output_file}")
    print(f"  - Molecules: {num_molecules}")
    print(f"  - Scaffold: {has_scaffold}")
    print(f"  - Protein: {has_protein}")


if __name__ == '__main__':
    main()
