# 03_virtual_screening/@job.toml
[container]
docker_file = "Dockerfile"

[scripts]
run = "./run.sh"

[env]
# Optional overrides (if not provided, the script will ask the user)
CENTER_X = ""
CENTER_Y = ""
CENTER_Z = ""
SIZE_X = ""
SIZE_Y = ""
SIZE_Z = ""
OUTDIR = "/work/out"
INDIR = "/work/in"
