"""Generate Markdown report from corrected properties."""
import json, pathlib, datetime

props  = json.loads(pathlib.Path("inputs/corrected_properties.json").read_text())
build  = json.loads(pathlib.Path("inputs/build_report.json").read_text())

# ── Helper ────────────────────────────────────────────────────────────────────
def fmt(val, digits=3, unit=""):
    if val is None:
        return "N/A"
    return f"{val:.{digits}f}{(' ' + unit) if unit else ''}"


resin       = props["resin_type"]
temp_c      = props["temperature_c"]
fiber_wt    = props["fiber_loading_wt_pct"]
gf_applied  = props["gf_correction_applied"]
E_md        = props.get("youngs_modulus_gpa")
E_corr      = props.get("corrected_youngs_modulus_gpa")
rho_md      = props.get("avg_density_kg_m3")
rho_corr    = props.get("corrected_density_kg_m3")
spec_mod    = props.get("corrected_specific_modulus_kNm_kg")
note        = props.get("note", "")
prod_time   = props.get("prod_time_ps", "?")
deform_time = props.get("deform_time_ps", "?")
n_chains    = build.get("n_chains", "?")
fiber_vf    = props.get("fiber_volume_fraction", 0.0)

# ── Density convergence from production XVG ───────────────────────────────────
xvg_lines = [l for l in pathlib.Path("inputs/density_prod.xvg").read_text().splitlines()
             if l and not l.startswith(("#", "@"))]
density_series = [float(l.split()[1]) for l in xvg_lines]
n_third = max(len(density_series) // 3, 1)
rho_final = sum(density_series[-n_third:]) / n_third
rho_init  = density_series[0] if density_series else 0

# ── Build Markdown ─────────────────────────────────────────────────────────────
lines = [
    f"# Polymer MD Report — {resin} @ {temp_c:.0f} °C / {fiber_wt:.0f} wt% GF",
    f"",
    f"*Generated by workflow-030 · {datetime.date.today()}*",
    f"",
    f"## Simulation Setup",
    f"",
    f"| Parameter | Value |",
    f"|---|---|",
    f"| Resin | {resin} |",
    f"| Temperature | {temp_c:.0f} °C |",
    f"| Glass-fiber loading | {fiber_wt:.0f} wt% (V_f = {fiber_vf:.3f}) |",
    f"| Chains in cell | {n_chains} × 5-mer oligomer |",
    f"| Force field | GAFF2 (AmberTools antechamber) |",
    f"| Production NPT | {prod_time} ps |",
    f"| Deformation NVT | {deform_time} ps (target 2% strain) |",
    f"",
    f"## Mechanical & Physical Properties",
    f"",
    f"| Property | MD (neat resin) | After GF correction |",
    f"|---|---|---|",
    f"| Young's modulus (GPa) | {fmt(E_md)} | {fmt(E_corr)} |",
    f"| Density (kg/m³) | {fmt(rho_md, 1)} | {fmt(rho_corr, 1)} |",
    f"| Specific modulus (kN·m/kg) | — | {fmt(spec_mod, 1)} |",
    f"",
]

if gf_applied:
    lines += [
        f"## Glass-Fiber Correction (Halpin-Tsai)",
        f"",
        f"Model: Halpin-Tsai longitudinal + transverse, Christensen-Waals random-orientation average.",
        f"",
        f"| Parameter | Value |",
        f"|---|---|",
        f"| Fiber type | E-glass |",
        f"| E_fiber | {props.get('E_fiber_gpa', 72.0)} GPa |",
        f"| Aspect ratio | {props.get('aspect_ratio', 20)} |",
        f"| V_f | {fiber_vf:.3f} |",
        f"",
        f"> **Note:** {note}",
        f"",
    ]

lines += [
    f"## Density Convergence",
    f"",
    f"Production NPT density (kg/m³): initial {rho_init:.1f} → final (last third avg) {rho_final:.1f}",
    f"",
    f"> **Simulation note:** Default run times (500 ps equil, 1 000 ps production) start from a",
    f"> 60 %-packed amorphous cell; full density convergence typically requires 5–10 ns.",
    f"> Increase `PARAM_EQUIL_TIME_PS` and `PARAM_PROD_TIME_PS` for production-quality results.",
    f"",
    f"## EV Lightweighting Context",
    f"",
    f"Specific modulus (E / ρ) is the key metric for lightweight structural components.",
    f"Higher specific modulus = stiffer material per unit mass → lighter part for the same stiffness.",
    f"",
    f"| Material (reference) | Specific modulus (kN·m/kg) |",
    f"|---|---|",
    f"| Steel | ~26 |",
    f"| Aluminium 6061 | ~26 |",
    f"| PP neat (typical) | ~1.4 |",
    f"| PP + 30 wt% GF (typical) | ~4–5 |",
    f"| PA6 + 30 wt% GF (typical) | ~7–9 |",
    f"| Carbon fibre composite | ~100–200 |",
    f"| **This run** | **{fmt(spec_mod, 1)}** |",
    f"",
]

report_md = "\n".join(lines)
pathlib.Path("outputs/report.md").write_text(report_md)

# ── Summary JSON for downstream aggregation ───────────────────────────────────
summary = {
    "resin_type":                   resin,
    "temperature_c":                temp_c,
    "fiber_loading_wt_pct":         fiber_wt,
    "youngs_modulus_gpa":           E_corr,
    "density_kg_m3":                rho_corr,
    "specific_modulus_kNm_kg":      spec_mod,
    "md_density_converged_kg_m3":   round(rho_final, 1),
    "gf_correction_applied":        gf_applied,
    "simulation_note":              note,
}
pathlib.Path("outputs/summary.json").write_text(json.dumps(summary, indent=2))

print(f"  Report written → outputs/report.md")
print(f"  Summary        → outputs/summary.json")
print(f"  Specific modulus: {fmt(spec_mod, 1)} kN·m/kg")
